RSYS-3135: Dropped subscribed events for create and update content
ezsystems/ezrecommendation-client pull request #40
Opened 2020-12-21 15:47 UTC by ciastektk

Dropped subscribing `CreateContentEvent` and `UpdateContentEvent` which are related to draft. Recommendation call with update action will be send after triggering `PublishVersionEvent`

2020-12-21 15:51 UTC, adamwojs requested changes

2020-12-21 15:51 UTC, adamwojs commented on src/lib/Service/ExportNotificationService.php
> +        exit;
Ups... :see\_no\_evil:

2020-12-21 18:40 UTC, Nattfarinn requested changes
Dat dump...

2020-12-22 08:51 UTC, adamwojs approved these changes

2020-12-22 09:07 UTC, Nattfarinn approved these changes

2020-12-22 09:08 UTC, merged